version: "3.7"

volumes:
  logs:
    driver: local

services:
  slim:
    env_file:
      - ./.env
    image: php:8-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
      - logs:/var/www/logs
